#!/usr/bin/env php
<?php
use MaplePHP\Http\Environment;
use MaplePHP\Http\ServerRequest;
use MaplePHP\Http\Uri;
use MaplePHP\Prompts\Command;
use MaplePHP\Unitary\Unit;

if (!class_exists(Unit::class)) {
    $dir = realpath(__DIR__ . "/../../../");
    $alFile = (defined("UNITARY_AUTOLOAD_FILE") ? UNITARY_AUTOLOAD_FILE : "$dir/vendor/autoload.php");
    if (is_file($alFile)) {
        require_once($alFile);
    } else {
        die("Please run 'composer install' before running the example test suite");
    }
}

$unit = new Unit();
$command = new Command();
$env = new Environment();
$request = new ServerRequest(new Uri($env->getUriParts([
    "argv" => $argv
])), $env);

$data = $request->getCliArgs();
$defaultPath = (defined("UNITARY_PATH") ? UNITARY_PATH : null);

try {
    $path = ($data['path'] ?? $defaultPath);
    if(!isset($path)) {
        throw new Exception("Path not specified: --path=path/to/dir");
    }

    $testDir = realpath($data['path']);
    if(!is_dir($testDir)) {
        throw new Exception("Test directory '$testDir' does not exist");
    }
    $unit->setArgs($data);
    $unit->executeAll($testDir);

} catch (Exception $e) {
    $command->error($e->getMessage());
}
